// ============================================================
// MealStack · Local Recipe Fallback
// Used when Supabase recipes tables are unavailable.
// ============================================================

import type { Recipe } from '@/types';

const now = new Date().toISOString();

export const LOCAL_RECIPES: Recipe[] = [
  {
    id: 'a1b2c3d4-0001-0000-0000-000000000001',
    name: 'Egg Fried Rice',
    description: 'Classic wok-style fried rice with scrambled egg and garlic butter.',
    emoji: '🍳',
    time_minutes: 20,
    servings: 2,
    difficulty: 'easy',
    created_at: now,
    recipe_ingredients: [
      {
        id: 'ri-egg-fried-rice-1',
        ingredient_id: 'ing-basmati-rice',
        quantity: 300,
        unit: 'g',
        quantity_base: 300,
        ingredient: {
          id: 'ing-basmati-rice',
          name: 'Basmati Rice',
          category: 'grain',
          default_unit: 'g',
          price_per_unit: 0.12,
          created_at: now,
        },
      },
      {
        id: 'ri-egg-fried-rice-2',
        ingredient_id: 'ing-eggs',
        quantity: 3,
        unit: 'pcs',
        quantity_base: 3,
        ingredient: {
          id: 'ing-eggs',
          name: 'Eggs',
          category: 'protein',
          default_unit: 'pcs',
          price_per_unit: 15,
          created_at: now,
        },
      },
      {
        id: 'ri-egg-fried-rice-3',
        ingredient_id: 'ing-garlic',
        quantity: 2,
        unit: 'pcs',
        quantity_base: 2,
        ingredient: {
          id: 'ing-garlic',
          name: 'Garlic',
          category: 'veg',
          default_unit: 'pcs',
          price_per_unit: 4,
          created_at: now,
        },
      },
      {
        id: 'ri-egg-fried-rice-4',
        ingredient_id: 'ing-butter',
        quantity: 20,
        unit: 'g',
        quantity_base: 20,
        ingredient: {
          id: 'ing-butter',
          name: 'Butter',
          category: 'dairy',
          default_unit: 'g',
          price_per_unit: 0.8,
          created_at: now,
        },
      },
    ],
  },
  {
    id: 'a1b2c3d4-0002-0000-0000-000000000002',
    name: 'Cheesy Pasta',
    description: 'Creamy cheddar pasta — comfort food in 25 minutes.',
    emoji: '🍝',
    time_minutes: 25,
    servings: 2,
    difficulty: 'easy',
    created_at: now,
    recipe_ingredients: [
      {
        id: 'ri-cheesy-pasta-1',
        ingredient_id: 'ing-spaghetti',
        quantity: 200,
        unit: 'g',
        quantity_base: 200,
        ingredient: {
          id: 'ing-spaghetti',
          name: 'Spaghetti',
          category: 'grain',
          default_unit: 'g',
          price_per_unit: 0.22,
          created_at: now,
        },
      },
      {
        id: 'ri-cheesy-pasta-2',
        ingredient_id: 'ing-cheddar-cheese',
        quantity: 80,
        unit: 'g',
        quantity_base: 80,
        ingredient: {
          id: 'ing-cheddar-cheese',
          name: 'Cheddar Cheese',
          category: 'dairy',
          default_unit: 'g',
          price_per_unit: 1.2,
          created_at: now,
        },
      },
      {
        id: 'ri-cheesy-pasta-3',
        ingredient_id: 'ing-butter',
        quantity: 30,
        unit: 'g',
        quantity_base: 30,
        ingredient: {
          id: 'ing-butter',
          name: 'Butter',
          category: 'dairy',
          default_unit: 'g',
          price_per_unit: 0.8,
          created_at: now,
        },
      },
    ],
  },
  {
    id: 'a1b2c3d4-0003-0000-0000-000000000003',
    name: 'Spiced Milk Oats',
    description: 'Warm oats with turmeric and cumin — a zero-waste breakfast.',
    emoji: '🥣',
    time_minutes: 10,
    servings: 1,
    difficulty: 'easy',
    created_at: now,
    recipe_ingredients: [
      {
        id: 'ri-spiced-oats-1',
        ingredient_id: 'ing-oats',
        quantity: 100,
        unit: 'g',
        quantity_base: 100,
        ingredient: {
          id: 'ing-oats',
          name: 'Oats',
          category: 'grain',
          default_unit: 'g',
          price_per_unit: 0.15,
          created_at: now,
        },
      },
      {
        id: 'ri-spiced-oats-2',
        ingredient_id: 'ing-whole-milk',
        quantity: 200,
        unit: 'ml',
        quantity_base: 200,
        ingredient: {
          id: 'ing-whole-milk',
          name: 'Whole Milk',
          category: 'dairy',
          default_unit: 'ml',
          price_per_unit: 0.06,
          created_at: now,
        },
      },
      {
        id: 'ri-spiced-oats-3',
        ingredient_id: 'ing-cumin',
        quantity: 5,
        unit: 'g',
        quantity_base: 5,
        ingredient: {
          id: 'ing-cumin',
          name: 'Cumin',
          category: 'spice',
          default_unit: 'g',
          price_per_unit: 0.5,
          created_at: now,
        },
      },
    ],
  },
  {
    id: 'a1b2c3d4-0004-0000-0000-000000000004',
    name: 'Chicken Rice Bowl',
    description: 'Spiced chicken thigh on fluffy basmati with garlic.',
    emoji: '🍚',
    time_minutes: 35,
    servings: 2,
    difficulty: 'medium',
    created_at: now,
    recipe_ingredients: [
      {
        id: 'ri-chicken-rice-1',
        ingredient_id: 'ing-chicken-breast',
        quantity: 300,
        unit: 'g',
        quantity_base: 300,
        ingredient: {
          id: 'ing-chicken-breast',
          name: 'Chicken Breast',
          category: 'protein',
          default_unit: 'g',
          price_per_unit: 0.67,
          created_at: now,
        },
      },
      {
        id: 'ri-chicken-rice-2',
        ingredient_id: 'ing-basmati-rice',
        quantity: 0.4,
        unit: 'kg',
        quantity_base: 400,
        ingredient: {
          id: 'ing-basmati-rice',
          name: 'Basmati Rice',
          category: 'grain',
          default_unit: 'g',
          price_per_unit: 0.12,
          created_at: now,
        },
      },
      {
        id: 'ri-chicken-rice-3',
        ingredient_id: 'ing-garlic',
        quantity: 3,
        unit: 'pcs',
        quantity_base: 3,
        ingredient: {
          id: 'ing-garlic',
          name: 'Garlic',
          category: 'veg',
          default_unit: 'pcs',
          price_per_unit: 4,
          created_at: now,
        },
      },
      {
        id: 'ri-chicken-rice-4',
        ingredient_id: 'ing-cumin',
        quantity: 10,
        unit: 'g',
        quantity_base: 10,
        ingredient: {
          id: 'ing-cumin',
          name: 'Cumin',
          category: 'spice',
          default_unit: 'g',
          price_per_unit: 0.5,
          created_at: now,
        },
      },
    ],
  },
  {
    id: 'a1b2c3d4-0005-0000-0000-000000000005',
    name: 'Spinach Omelette',
    description: 'Protein-packed omelette with wilted spinach and butter.',
    emoji: '🥬',
    time_minutes: 15,
    servings: 1,
    difficulty: 'easy',
    created_at: now,
    recipe_ingredients: [
      {
        id: 'ri-spinach-omelette-1',
        ingredient_id: 'ing-eggs',
        quantity: 3,
        unit: 'pcs',
        quantity_base: 3,
        ingredient: {
          id: 'ing-eggs',
          name: 'Eggs',
          category: 'protein',
          default_unit: 'pcs',
          price_per_unit: 15,
          created_at: now,
        },
      },
      {
        id: 'ri-spinach-omelette-2',
        ingredient_id: 'ing-spinach',
        quantity: 150,
        unit: 'g',
        quantity_base: 150,
        ingredient: {
          id: 'ing-spinach',
          name: 'Spinach',
          category: 'veg',
          default_unit: 'g',
          price_per_unit: 0.15,
          created_at: now,
        },
      },
      {
        id: 'ri-spinach-omelette-3',
        ingredient_id: 'ing-butter',
        quantity: 15,
        unit: 'g',
        quantity_base: 15,
        ingredient: {
          id: 'ing-butter',
          name: 'Butter',
          category: 'dairy',
          default_unit: 'g',
          price_per_unit: 0.8,
          created_at: now,
        },
      },
      {
        id: 'ri-spinach-omelette-4',
        ingredient_id: 'ing-garlic',
        quantity: 1,
        unit: 'pcs',
        quantity_base: 1,
        ingredient: {
          id: 'ing-garlic',
          name: 'Garlic',
          category: 'veg',
          default_unit: 'pcs',
          price_per_unit: 4,
          created_at: now,
        },
      },
    ],
  },
  {
    id: 'a1b2c3d4-0006-0000-0000-000000000006',
    name: 'Milk Tea',
    description: 'Quick stovetop milk tea with tea leaf and sugar.',
    emoji: '☕',
    time_minutes: 8,
    servings: 2,
    difficulty: 'easy',
    created_at: now,
    recipe_ingredients: [
      {
        id: 'ri-milk-tea-1',
        ingredient_id: 'ing-whole-milk',
        quantity: 250,
        unit: 'ml',
        quantity_base: 250,
        ingredient: {
          id: 'ing-whole-milk',
          name: 'Whole Milk',
          category: 'dairy',
          default_unit: 'ml',
          price_per_unit: 0.06,
          created_at: now,
        },
      },
      {
        id: 'ri-milk-tea-2',
        ingredient_id: 'ing-tea-leaf',
        quantity: 6,
        unit: 'g',
        quantity_base: 6,
        ingredient: {
          id: 'ing-tea-leaf',
          name: 'Tea Leaf',
          category: 'spice',
          default_unit: 'g',
          price_per_unit: 0.3,
          created_at: now,
        },
      },
      {
        id: 'ri-milk-tea-3',
        ingredient_id: 'ing-sugar',
        quantity: 10,
        unit: 'g',
        quantity_base: 10,
        ingredient: {
          id: 'ing-sugar',
          name: 'Sugar',
          category: 'spice',
          default_unit: 'g',
          price_per_unit: 0.07,
          created_at: now,
        },
      },
    ],
  },
  {
    id: 'a1b2c3d4-0007-0000-0000-000000000007',
    name: 'Egg Fry',
    description: 'Simple pan-fried egg with oil and salt.',
    emoji: '🍳',
    time_minutes: 6,
    servings: 1,
    difficulty: 'easy',
    created_at: now,
    recipe_ingredients: [
      {
        id: 'ri-egg-fry-1',
        ingredient_id: 'ing-eggs',
        quantity: 2,
        unit: 'pcs',
        quantity_base: 2,
        ingredient: {
          id: 'ing-eggs',
          name: 'Eggs',
          category: 'protein',
          default_unit: 'pcs',
          price_per_unit: 15,
          created_at: now,
        },
      },
      {
        id: 'ri-egg-fry-2',
        ingredient_id: 'ing-olive-oil',
        quantity: 10,
        unit: 'ml',
        quantity_base: 10,
        ingredient: {
          id: 'ing-olive-oil',
          name: 'Olive oil',
          category: 'spice',
          default_unit: 'ml',
          price_per_unit: 0.2,
          created_at: now,
        },
      },
      {
        id: 'ri-egg-fry-3',
        ingredient_id: 'ing-salt',
        quantity: 2,
        unit: 'g',
        quantity_base: 2,
        ingredient: {
          id: 'ing-salt',
          name: 'Salt',
          category: 'spice',
          default_unit: 'g',
          price_per_unit: 0.02,
          created_at: now,
        },
      },
    ],
  },
];
